# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - todo-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/tododb
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - todo-net

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - todo-net

volumes:
  mongo-data:

networks:
  todo-net: